### ISSUE TITLE
2-Traefik deploy script issues

### ISSUE THREAD

**Issue by PARitter** [carlosedp/kubernetes-arm#1]
The deploy script for Traefik has a couple of issues:

1. It checks for Helm being installed (though it does not appear to use it).  Only a minor issue because your article describes installing Traefik before Helm.

2. The script sets the namespace to Traefik but 3 of the 4 yaml files have the namespace hard coded to kube-system, which causes them to fail when applied with the script.

Traefik installs fine if you just directly apply the yaml files.

**Comment by carlosedp** [comment]
Thanks for reporting, fixed on https://github.com/carlosedp/kubernetes-arm/commit/0e60a1c90d29410e85573452d31ca8184b59d534.

Helm is only needed for external Ingresses since it deploys a Consul cluster. Added a note to it's script.
