### ISSUE TITLE
test-pod.yaml wrong busybox for rpi

### ISSUE THREAD

**Issue by VladoPortos** [carlosedp/kubernetes-arm#2]
Hello,
in test-pod.yaml you use:
 image: gcr.io/google_containers/busybox:1.24
This will fail on rpi since its not arm ach build ( I assume that was it, cause it caused me so much headache to figure out :D ) 

When I switched to docker image:
image: arm32v7/busybox

It worked ;)

**Comment by carlosedp** [comment]
You can also use my busybox 1.31 image that is multi-arch:

```
❯ query-manifest carlosedp/busybox:1.31
Image: carlosedp/busybox:1.31
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm
   - linux/arm64
   - linux/ppc64le
   - linux/riscv64
```
