### ISSUE TITLE
svclb pods for external are failing to schedule

### ISSUE THREAD

**Issue by mickkael** [carlosedp/kubernetes-arm#5]
Hi,

very good job on this project. I have tried to reproduce the same without success for now. 
Need some help on the following.
After deploying the external ingress, I am getting this errors:

kube-system:svclb-traefik-ingress-service-external-6p2m2  
FailedScheduling 
0/5 nodes are available: 1 node(s) didn't match node selector, 4 node(s) didn't have free ports for the requested pod ports.

I understand that this is a conflict with the internal ingress controller deployment, but I don't know how to resolve.

k3s v1.17.4+k3s1
metallb v0.9
traefik v1.7

**Comment by carlosedp** [comment]
Probably you see port conflicts because K3s already has it's Traefik instance and uses an internal load balancer that conflicts with MetalLB.
This repo is for running vanilla Kubernetes and not K3s.

**Comment by mickkael** [comment]
Issue resolved, I put the details here if anyone else is facing the same. Indeed @carlosedp was right, k3s has an integrated load balancer, that conflicts with metallb.
To disable the integrated lb, edit your startup script and add --no-deploy servicelb (location may vary depending on your distro):
And then restart, `sudo service k3s restart`

`sudo cat /lib/systemd/system/k3s.service`

```
[Unit]
Description=Lightweight Kubernetes
Documentation=https://k3s.io
After=network-online.target

[Service]
Type=notify
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s server  --no-deploy traefik --no-deploy servicelb
KillMode=process
Delegate=yes
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=infinity
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target

```

**Comment by carlosedp** [comment]
Nice! Thanks!
