### ISSUE TITLE
2-Traefik no matches for kind Deployment

### ISSUE THREAD

**Issue by independentid** [carlosedp/kubernetes-arm#6]
Just running your Traefik deployment. Wondering if recent updates may have changed things.

When running deploy, the last step generates this error:
error: unable to recognize "traefik-internal-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by carlosedp** [comment]
It's been a while since I updated this repo. Some APIs have been deprecated like the `Deployment` that changed from `extensions/v1beta1` to `apps/v1`.

**Comment by carlosedp** [comment]
Updated on f34db69.

**Comment by independentid** [comment]
Thanks. I also received...
error: error validating "3-deployment-arm.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by YushchenkoAndrew** [comment]
Also have the same issue

**Comment by YushchenkoAndrew** [comment]
I can solve this issue by adding to this to the file "3-deployment-arm.yaml"

     replicas: 2
     selector:
       matchLabels:
        app: nfs-client-provisioner
       strategy:

After that pods creating fine.
